# Exercise 2.03: Preparing the Quandl Data for Prediction

The goal of this exercise is to download an external dataset from the Quandl library and then prepare it so that it is ready for use in our linear regression models.

The following steps will help you to complete this exercise:

  > **Note**  
  > You need to install Qaundl library

1.- Download the data into a DataFrame using Quandl for the S&P 500 between 1950 and 2019. Its ticker is `“YALE/SPCOMP”`:

In [3]:
import quandl

data_frame = quandl.get("YALE/SPCOMP", start_date="1950-01-01", end_date="2019-12-31")

2.- Use the `head()` method to visualize the columns inside the `data_frame.head()` DataFrame.

Output:

![Figure 2.18](img/fig2_18.jpg)

In [4]:
data_frame.head()

,S&P Composite,Dividend,Earnings,CPI,Long Interest Rate,Real Price,Real Dividend,Real Earnings,Cyclically Adjusted PE Ratio
Year,,,,,,,,,
1950-01-31,16.88,1.15,2.33667,23.5,2.320000,187.229907,12.755592,25.917921,10.745733
1950-02-28,17.21,1.16,2.35333,23.5,2.340833,190.890208,12.866510,26.102711,10.911564
1950-03-31,17.35,1.17,2.37000,23.6,2.361667,191.627626,12.922439,26.176223,10.910947
1950-04-30,17.84,1.18,2.42667,23.6,2.382500,197.039587,13.032887,26.802133,11.178022
1950-05-31,18.44,1.19,2.48333,23.7,2.403333,202.807127,13.087879,27.312203,11.461543

A few features seem to highly correlate with each other. For instance, the `Real Dividend` column grows proportionally with `Real Price`. The ratio between them is not always similar, but they do correlate.

As regression is not about detecting the correlation between features, we would rather get rid of the features that we know are correlated and perform regression on the features that are non-correlated. In this case, we will keep the `Long Interest Rate`, `Real Price`, and `Real Dividend` columns.

3.- Keep only the relevant columns in the `Long Interest Rate`, `Real Price`, and `Real Dividend` DataFrames:

Output:

![Figure 2.19](img/fig2_19.jpg)

In [5]:
data_frame = data_frame[['Long Interest Rate', 'Real Price', 'Real Dividend']]
data_frame

            Long Interest Rate   Real Price  Real Dividend
Year
1950-01-31            2.320000   187.229907      12.755592
1950-02-28            2.340833   190.890208      12.866510
1950-03-31            2.361667   191.627626      12.922439
1950-04-30            2.382500   197.039587      13.032887
1950-05-31            2.403333   202.807127      13.087879
...                        ...          ...            ...
2019-08-31            1.630000  2943.799674      57.747370
2019-09-30            1.700000  3027.438466      58.088856
2019-10-31            1.710000  3015.999351      58.300732
2019-11-30            1.810000  3146.548400      58.676572
2019-12-31            1.860000  3222.288571      59.074877

[840 rows x 3 columns]

You can see that the DataFrame contains a few missing values `NaN`. As regression doesn't work with missing values, we need to either replace them or delete them. In the real world, we will usually choose to replace them. In this case, we will replace the missing values by the preceding values using a method called **forward filling**.

4.- Replace the missing values with a forward filling.

Output:

![Figure 2.20](img/fig2_20.jpg)

In [6]:
data_frame.fillna(method='ffill', inplace=True)
data_frame

            Long Interest Rate   Real Price  Real Dividend
Year
1950-01-31            2.320000   187.229907      12.755592
1950-02-28            2.340833   190.890208      12.866510
1950-03-31            2.361667   191.627626      12.922439
1950-04-30            2.382500   197.039587      13.032887
1950-05-31            2.403333   202.807127      13.087879
...                        ...          ...            ...
2019-08-31            1.630000  2943.799674      57.747370
2019-09-30            1.700000  3027.438466      58.088856
2019-10-31            1.710000  3015.999351      58.300732
2019-11-30            1.810000  3146.548400      58.676572
2019-12-31            1.860000  3222.288571      59.074877

[840 rows x 3 columns]

Now that we have cleaned the missing data, we need to create our label. We want to predict the `Real Price` column 3 months in advance using the current `Real Price`, `Long Interest` Rate, and `Real Dividend` columns. In order to create our label, we need to shift the `Real Price` values up by three units and call it `Real Price Label`.

6.- Create the `Real Price Label` label by shifting `Real Price` by 3 months.

Output:

![Figure 2.21](img/fig2_21.jpg)

In [7]:
data_frame['Real Price Label'] = data_frame['Real Price'].shift(-3)
data_frame

            Long Interest Rate   Real Price  Real Dividend  Real Price Label
Year
1950-01-31            2.320000   187.229907      12.755592        197.039587
1950-02-28            2.340833   190.890208      12.866510        202.807127
1950-03-31            2.361667   191.627626      12.922439        205.240598
1950-04-30            2.382500   197.039587      13.032887        187.976419
1950-05-31            2.403333   202.807127      13.087879        197.692277
...                        ...          ...            ...               ...
2019-08-31            1.630000  2943.799674      57.747370       3146.548400
2019-09-30            1.700000  3027.438466      58.088856       3222.288571
2019-10-31            1.710000  3015.999351      58.300732               NaN
2019-11-30            1.810000  3146.548400      58.676572               NaN
2019-12-31            1.860000  3222.288571      59.074877               NaN

[840 rows x 4 columns]

The side effect of shifting these values is that missing values will appear in the last three rows for `Real Price Label`, so we need to remove the last three rows of data. However, before that, we need to convert the features into a NumPy array and scale it. We can use the `drop` method of the DataFrame to remove the label column and the preprocessing function from `sklearn` to scale the features.

6.- Create a NumPy array for the features and scale it.

Output:

```
array([[-1.14834808, -1.13030753, -1.19145337],
       [-1.14109376, -1.12504171, -1.17960932],
       [-1.13383944, -1.12398084, -1.17363711],
       ...,
       [-1.36075461,  2.93924962,  3.67194058],
       [-1.32593387,  3.12706161,  3.7120735 ],
       [-1.3085235 ,  3.23602381,  3.75460521]])
```

In [11]:
import numpy as np
from sklearn import preprocessing

features = np.array(data_frame.drop('Real Price Label', 1))
scaled_features = preprocessing.scale(features)
scaled_features

array([[-1.14834808, -1.13030753, -1.19145337],
       [-1.14109376, -1.12504171, -1.17960932],
       [-1.13383944, -1.12398084, -1.17363711],
       ...,
       [-1.36075461,  2.93924962,  3.67194058],
       [-1.32593387,  3.12706161,  3.7120735 ],
       [-1.3085235 ,  3.23602381,  3.75460521]])

The `1 in the second argument specifies that we are dropping columns. As the original DataFrame was not modified, the label can be directly extracted from it. Now that the features are scaled, we need to remove the last three values of the features as they are the features of the missing values in the label column. We will save them for later in the prediction part.

7.- Remove the last three values of the features array and save them into another array

Output:

```
array([[-1.14834808, -1.13030753, -1.19145337],
       [-1.14109376, -1.12504171, -1.17960932],
       [-1.13383944, -1.12398084, -1.17363711],
       ...,
       [-1.07522452,  2.86136628,  3.47166907],
       [-1.12049149,  2.78043332,  3.50007195],
       [-1.23888201,  2.83151407,  3.54006023]])
```

In [12]:
scaled_features_latest_3 = scaled_features[-3:]
scaled_features = scaled_features[:-3]
scaled_features

array([[-1.14834808, -1.13030753, -1.19145337],
       [-1.14109376, -1.12504171, -1.17960932],
       [-1.13383944, -1.12398084, -1.17363711],
       ...,
       [-1.38861121,  2.97929738,  3.57121717],
       [-1.38861121,  2.83538088,  3.61285159],
       [-1.36423669,  2.95570629,  3.64931605]])

The `scaled_features` variable doesn't contain the three data points anymore as they are now in `scaled_features_latest_3`. Now we can remove the last three rows with missing data from the DataFrame, then convert the label into a NumPy array using `sklearn`.

8.- Remove the rows with missing data

Output:

![Figure 2.22](img/fig2_22.jpg)

In [13]:
data_frame.dropna(inplace=True)
data_frame

            Long Interest Rate   Real Price  Real Dividend  Real Price Label
Year
1950-01-31            2.320000   187.229907      12.755592        197.039587
1950-02-28            2.340833   190.890208      12.866510        202.807127
1950-03-31            2.361667   191.627626      12.922439        205.240598
1950-04-30            2.382500   197.039587      13.032887        187.976419
1950-05-31            2.403333   202.807127      13.087879        197.692277
...                        ...          ...            ...               ...
2019-05-31            2.400000  2905.605351      56.691201       2943.799674
2019-06-30            2.060000  2941.111837      57.065687       3027.438466
2019-07-31            1.630000  3043.836752      57.357468       3015.999351
2019-08-31            1.630000  2943.799674      57.747370       3146.548400
2019-09-30            1.700000  3027.438466      58.088856       3222.288571

[837 rows x 4 columns]

9.- Now let's see if we have accurately created our label.

Output:

![Figure 2.23](img/fig2_23.jpg)

In [14]:
label = np.array(data_frame['Real Price Label'])
label

array([ 197.03958729,  202.807127  ,  205.24059811,  187.97641888,
        197.69227706,  203.82581434,  210.53941026,  209.26490617,
        205.9196225 ,  217.65948337,  223.13114786,  218.52818343,
        221.45805736,  220.70364701,  216.87932481,  220.70364701,
        230.36509257,  234.49210613,  232.4032458 ,  224.2249054 ,
        230.26407274,  237.93626311,  235.38485029,  235.97950675,
        234.39450701,  234.29577301,  239.80513   ,  244.84256067,
        245.81880693,  241.91382191,  236.83734139,  244.35443755,
        254.21452472,  256.54210132,  254.36261943,  254.68026024,
        242.13733092,  242.49956966,  232.93854897,  236.24540103,
        236.33615325,  225.48348857,  231.40615806,  237.40203996,
        240.59970009,  246.70432398,  252.13065632,  257.46008987,
        268.73035942,  278.3902289 ,  280.61890112,  291.95605976,
        297.76998727,  305.88381483,  312.98382071,  325.23862537,
        341.39331526,  347.54366667,  359.1609971 ,  356.32988296,
        368.63058577,  367.06859176,  388.35076011,  415.20445326,
        412.67568405,  429.64924294,  408.04081236,  435.56006924,
        441.27022826,  429.40446502,  432.12775494,  461.88942341,
        465.5986947 ,  449.29672907,  443.40566517,  464.04689945,
        462.9778131 ,  445.59156971,  438.28415855,  433.734496  ,
        438.58499674,  429.04643415,  409.05387699,  412.83311987,
        420.88285439,  435.48462661,  441.07743817,  446.80238348,
        422.21029187,  405.07872244,  379.84189435,  370.33592298,
        370.15236118,  374.76386993,  376.03981696,  381.12145321,
        381.8771327 ,  394.14337976,  403.61364403,  413.27735672,
        430.22057699,  441.58489412,  459.53329974,  471.88040948,
        482.44231998,  499.9235881 ,  493.9870231 ,  506.52384913,
        513.22612155,  520.95597207,  514.68708986,  533.27719127,
        530.24213527,  507.52643814,  505.35686224,  507.39602151,
        523.62063656,  516.2446837 ,  494.54045221,  487.80236071,
        492.4222511 ,  487.91596458,  504.23185017,  491.72732297,
        497.62734637,  482.65713775,  469.97117139,  485.19078498,
        496.82416779,  522.36512852,  543.79504421,  560.85150772,
        575.80871418,  581.6691401 ,  573.97186426,  568.58143867,
        590.96952751,  584.3946755 ,  590.82423333,  617.58509567,
        623.31956617,  600.12102642,  608.08595365,  608.69213447,
        587.34304263,  543.66992293,  480.14538518,  490.0881854 ,
        503.42216271,  497.30754934,  481.61663873,  514.79905625,
        537.09215329,  557.84188207,  565.21575263,  561.2260473 ,
        587.63366852,  599.42736344,  597.21290368,  586.4374851 ,
        602.65430277,  618.53150122,  618.04660657,  614.57681185,
        625.66295526,  644.89595429,  652.82534862,  664.71944013,
        674.33593964,  680.91564984,  674.68315677,  697.4899664 ,
        689.48179032,  699.08240924,  711.15144976,  713.80122308,
        701.43668878,  719.48222532,  724.74550681,  723.09624385,
        730.25676011,  741.13133503,  701.46629937,  700.39397318,
        713.42686068,  737.26549668,  751.46724834,  757.71645623,
        751.89105055,  764.92393805,  755.01146398,  721.72152087,
        739.20278328,  700.30586827,  692.35203596,  688.45726954,
        642.87607148,  620.23790604,  611.08000783,  641.66173777,
        644.35546527,  669.07437652,  692.12951489,  706.3035153 ,
        716.29694683,  726.93677929,  715.67381629,  725.86159663,
        735.21047157,  743.26247106,  739.89674674,  714.57239985,
        732.76352729,  726.47837419,  691.6576261 ,  677.02620838,
        724.91648089,  739.43692732,  754.93094741,  749.11095487,
        730.66091007,  752.26866311,  766.4666983 ,  776.08267938,
        781.97325   ,  746.82838483,  739.01568785,  716.98932341,
        727.40027755,  749.03298489,  706.05489986,  670.8395517 ,
        663.47964581,  664.00981004,  667.50746059,  668.7435234 ,
        629.93441916,  622.75135985,  597.86656553,  604.90339103,
        581.90996396,  513.61731775,  507.81235367,  506.07704692,
        520.78081744,  549.11012742,  558.16483166,  554.75341338,
        589.75453235,  612.28374491,  634.39784718,  649.0377975 ,
        669.51990648,  657.14211911,  640.21652291,  634.03236486,
        621.23430417,  635.03383211,  620.03404639,  591.29159034,
        628.93987999,  655.13249574,  663.95146005,  678.08791486,
        683.36296867,  674.8278768 ,  675.08482014,  666.88569928,
        688.88119643,  677.33866627,  675.36854374,  707.58742983,
        720.64201471,  724.45722066,  693.87214569,  676.6265843 ,
        659.41628039,  636.50366287,  618.03014027,  622.5189605 ,
        599.91739357,  608.97031858,  627.63642434,  579.23944444,
        534.74332348,  537.59262559,  516.06921054,  531.34918745,
        502.09199094,  480.92963873,  477.64202801,  418.47704762,
        396.35617465,  350.9092081 ,  354.20888767,  363.09877641,
        336.84615207,  363.01969942,  397.68925286,  414.38152362,
        417.44658941,  441.4523172 ,  449.34283769,  444.80138925,
        411.43601754,  404.21047056,  420.51834094,  424.5468995 ,
        416.5827464 ,  454.08830333,  469.93135573,  471.42215608,
        473.45855125,  466.87724425,  467.16477025,  475.66615674,
        469.09312848,  477.42001085,  458.73963256,  454.80283276,
        468.91523067,  462.50041795,  445.45571489,  440.70873361,
        430.30250229,  426.90811592,  426.37080721,  428.16240246,
        416.32835069,  408.51946714,  396.65677735,  397.00828223,
        393.79887448,  376.389791  ,  368.73333219,  365.16752926,
        378.17809081,  393.65382058,  390.42693044,  385.5909699 ,
        410.33848826,  407.25323647,  390.79239419,  366.27441398,
        370.04160048,  380.52978408,  370.54140062,  373.80860709,
        376.95688775,  363.57199171,  366.65135788,  366.20452702,
        379.33119715,  379.45618834,  362.21721908,  356.12923155,
        366.34818057,  371.55455623,  380.91050158,  340.70994288,
        331.4536821 ,  343.18874908,  361.2016705 ,  377.59127509,
        386.44936525,  392.53815923,  400.20800767,  413.69890848,
        403.21911501,  398.47679023,  380.75603072,  392.31200339,
        393.1807138 ,  382.27868235,  380.62936341,  367.36807342,
        365.9939805 ,  330.85635005,  334.33403051,  341.88727295,
        343.29180266,  324.23281098,  315.48955999,  305.61776402,
        319.43620996,  316.70732881,  294.7851049 ,  292.47136256,
        292.67303147,  325.88874974,  352.23302877,  367.31464566,
        372.29190932,  384.5901158 ,  390.85350051,  404.43219842,
        416.89378474,  431.18887878,  435.91406633,  435.73417668,
        422.46325948,  432.79022642,  432.79509579,  425.50059585,
        423.02205429,  425.64719921,  400.40492261,  399.87845858,
        398.44482444,  394.76792698,  384.82836572,  378.34184462,
        410.0682689 ,  412.33573595,  407.94299335,  411.65606671,
        407.20037868,  423.97033081,  444.83949976,  439.49248449,
        440.36285921,  449.16698952,  457.60454438,  465.46026786,
        454.46161412,  443.09410688,  446.49929209,  472.29271216,
        494.36735201,  495.15459443,  523.22333349,  556.53304527,
        571.23889963,  570.86201446,  583.92096872,  571.78074475,
        582.14356199,  563.65464451,  561.01677108,  578.68853736,
        586.42096516,  619.99977406,  656.08209655,  680.12838426,
        669.10636269,  666.27900553,  692.17837753,  710.2809163 ,
        750.53026967,  722.36195587,  633.44580703,  553.3895039 ,
        544.35457322,  564.34543107,  579.96349375,  594.47866245,
        584.53223868,  568.12297681,  597.96655021,  591.92405506,
        577.60881239,  583.10748748,  601.55124667,  587.1841251 ,
        598.10678734,  614.2999327 ,  630.20870477,  623.83093561,
        640.10428777,  660.90846305,  679.89455016,  695.43655326,
        725.07203973,  724.2114926 ,  720.95941361,  704.33492097,
        720.58121848,  695.57154841,  672.92463662,  685.48735093,
        683.85754767,  706.62056453,  723.15971149,  719.66725255,
        655.11056848,  619.54831144,  599.64949948,  614.22109116,
        640.44271534,  630.32311328,  700.48869818,  718.79753459,
        732.00099497,  726.5930894 ,  725.03103123,  727.67912102,
        743.04632394,  735.617207  ,  733.93937642,  729.99302525,
        734.35926361,  785.33292266,  775.87995195,  762.25083302,
        761.251426  ,  773.96879941,  759.04949781,  770.0071113 ,
        773.14899544,  771.97491309,  758.26037994,  776.17269725,
        800.23215088,  795.55450584,  804.55994532,  817.11485195,
        802.02941576,  804.83955054,  808.79717081,  807.40723682,
        817.48966856,  824.97908415,  829.91853277,  827.54366185,
        833.0142566 ,  843.28665645,  837.90716936,  821.30211296,
        790.86815151,  796.81748797,  801.04705698,  792.86326381,
        812.13257624,  814.70376801,  808.66669584,  802.71095075,
        792.57716247,  806.85973511,  832.44653996,  849.03150206,
        871.56469916,  897.07710925,  921.87381943,  952.6741647 ,
        953.14816614,  984.73163164,  988.56613943, 1010.60878813,
       1043.59891477, 1037.2625308 , 1093.01249151, 1083.26146623,
       1079.26984048, 1100.60487888, 1111.99557036, 1069.31106396,
       1098.10983961, 1114.78265095, 1155.02833427, 1209.06738299,
       1221.52504847, 1255.31854937, 1303.92569563, 1290.51652025,
       1242.97300223, 1356.34831323, 1424.9019323 , 1502.70410902,
       1503.0615181 , 1515.14593614, 1534.20312803, 1515.39798533,
       1555.17172268, 1553.88149777, 1648.21349589, 1730.48141142,
       1784.02184338, 1774.68220673, 1772.45670873, 1847.25208637,
       1714.24743761, 1626.14746919, 1640.98358014, 1818.93017581,
       1892.59155209, 1981.1416827 , 1975.26284495, 2024.69461736,
       2093.35462329, 2089.13579448, 2074.20521819, 2159.36260451,
       2070.7394168 , 2046.40396854, 2014.61166217, 2154.33707813,
       2212.69467778, 2201.36896814, 2132.03609683, 2195.81316371,
       2223.67080876, 2155.9055698 , 2210.38981549, 2221.92630642,
       2240.72141965, 2202.98566429, 2082.47565853, 2063.1637324 ,
       1993.77712188, 1988.24849019, 1936.028766  , 1754.26216139,
       1753.19964534, 1863.43154681, 1813.92899721, 1768.72803937,
       1730.62061056, 1527.16495771, 1579.18698409, 1659.86385017,
       1688.93535771, 1678.17376131, 1613.60048196, 1682.01513072,
       1611.9753724 , 1564.59886923, 1469.21718541, 1307.76089019,
       1316.34327483, 1249.73150291, 1228.71446708, 1308.22011284,
       1295.62319317, 1285.12734595, 1191.5803194 , 1198.04924475,
       1262.20466394, 1329.5107776 , 1401.90450191, 1406.81480797,
       1397.23002902, 1434.79987397, 1463.52986301, 1483.27681152,
       1528.36240347, 1593.95310491, 1600.56737401, 1563.36231507,
       1571.37801883, 1520.08542329, 1556.47165467, 1521.9027077 ,
       1497.83984319, 1534.10606037, 1525.45544724, 1595.25272401,
       1642.58213546, 1614.80688216, 1630.30686461, 1611.27752444,
       1559.70043079, 1579.87558472, 1611.18652924, 1630.43156786,
       1624.82415271, 1607.37197626, 1559.70688599, 1632.23724756,
       1671.58702511, 1680.84157669, 1674.72932329, 1687.80459202,
       1684.46998669, 1660.4992794 , 1609.89882981, 1614.20797474,
       1645.44199565, 1692.84940111, 1761.02855894, 1796.32644149,
       1829.53840562, 1833.93773832, 1850.61507526, 1785.87216761,
       1845.83914348, 1894.16805243, 1894.3199896 , 1902.96087356,
       1823.60257365, 1871.72493012, 1920.80020372, 1814.87006082,
       1835.73366925, 1702.5984432 , 1668.25244927, 1607.61407068,
       1662.87421106, 1688.39399514, 1597.72962177, 1489.93839359,
       1524.62999412, 1449.87247118, 1166.00512622, 1083.54110656,
       1088.0701671 , 1068.56554679,  989.14403412,  927.80184316,
       1036.75140997, 1099.89974645, 1119.1849315 , 1132.70305504,
       1219.42766157, 1260.69043595, 1287.34256357, 1311.02425943,
       1340.26623159, 1351.580089  , 1309.84905943, 1379.81611483,
       1431.5497857 , 1344.11172627, 1295.55745207, 1291.02769333,
       1298.17856288, 1338.94976685, 1396.27822444, 1428.22525238,
       1476.48459185, 1518.11955747, 1556.0151945 , 1521.59123404,
       1543.17092787, 1543.78960101, 1486.5281851 , 1528.93938493,
       1363.79190736, 1348.59301055, 1389.7617666 , 1413.05696749,
       1436.07090702, 1495.62683473, 1548.50371074, 1578.59111307,
       1570.65312529, 1521.27763785, 1503.30453887, 1547.05808408,
       1587.90566518, 1625.87393426, 1620.19620739, 1578.87351264,
       1614.67463664, 1675.68930476, 1697.90288803, 1736.60973752,
       1760.69052266, 1834.92671987, 1807.01378121, 1861.99410208,
       1861.32839782, 1878.17986012, 1919.70382594, 1994.66048009,
       2021.94331362, 2030.69587925, 2017.30786588, 2055.67211166,
       2049.73095522, 2070.54727288, 2129.38537506, 2158.67285005,
       2149.6056218 , 2182.70245066, 2126.76603228, 2256.74680995,
       2280.38343906, 2262.06675622, 2312.27395408, 2296.15369124,
       2307.87743889, 2314.89467646, 2292.99695772, 2287.21840231,
       2231.10460268, 2130.01128697, 2219.08365685, 2285.07149276,
       2263.65868775, 2110.86612618, 2093.54197931, 2213.21341782,
       2261.1524086 , 2241.20158479, 2253.69922017, 2327.7733222 ,
       2349.50090041, 2329.55009608, 2310.83060537, 2338.15789393,
       2425.53398424, 2442.06103707, 2493.02799351, 2530.46532153,
       2514.97781875, 2551.21516699, 2590.02003193, 2613.22209716,
       2607.67101   , 2632.60958642, 2702.07476091, 2740.6952109 ,
       2817.0923303 , 2933.76282825, 2831.91327795, 2823.02806995,
       2760.72747173, 2798.87874242, 2849.10322956, 2889.5499183 ,
       2954.2920812 , 2995.96520991, 2871.07474273, 2816.36501056,
       2663.62001868, 2700.05566192, 2840.75865258, 2875.19027327,
       2961.86225073, 2905.60535082, 2941.11183721, 3043.83675162,
       2943.79967377, 3027.43846607, 3015.99935115, 3146.54840026,
       3222.28857079])

Our variable contains all the labels and is exactly the same as the `Real Price Label` column in the DataFrame.

Our next task is to separate the training and testing data from each other. As we saw in the Splitting Data into Training and Testing section, we will use $90\%$ of the data as the training data and the remaining $10\%$ as the test data.

10.- Split the `features` data into training and test sets using `sklearn`.

In [15]:
from sklearn import model_selection

model_selection.train_test_split(scaled_features, label, test_size=0.1, random_state=8)

[array([[ 1.18812373, -0.85394454, -0.49680704],
        [ 1.60945472, -0.7573144 , -0.54090236],
        [ 0.39072873, -0.63036375, -0.51721422],
        ...,
        [ 2.36506483, -0.85167251, -0.52509427],
        [ 0.95134269, -0.83333957, -0.45054375],
        [ 1.09410773, -0.31992582, -0.45789618]]),
 array([[ 0.79813142, -0.66075629, -0.26290003],
        [ 1.13937469, -0.50836061, -0.07220413],
        [ 0.06341375,  1.76962243,  0.06638872],
        [ 1.1115181 , -0.87272845, -0.46669502],
        [-0.56335961, -0.53266486, -0.55288764],
        [-1.34682631,  0.93120309,  1.07351628],
        [-0.65389354, -0.72080032, -0.88031204],
        [-0.67130391,  0.68616998,  1.11677031],
        [-0.17684937,  0.91638896,  0.66194473],
        [-0.33702478,  0.98827021, -0.08396135],
        [ 0.74938238, -0.72481019, -0.70118403],
        [ 0.84339838, -0.87432084, -0.44624972],
        [-0.35791723, -0.36917496, -0.11493309],
        [-0.52505679, -0.51052101, -0.53529094],
        [-0.18033144,  1.32556623,  0.94250257],
        [ 1.09062566, -0.45719962, -0.06134075],
        [ 2.76550337, -0.84603614, -0.59148433],
        [ 1.82186125, -0.77254264, -0.61216629],
        [ 0.61009941, -0.78061561, -0.58352311],
        [-1.02299341,  2.68714281,  3.45232287],
        [-0.50416435,  0.9457486 ,  0.34399151],
        [ 1.4492793 , -0.88002625, -0.55435238],
        [ 0.20269672,  0.33974016,  0.04731765],
        [-0.30916819,  1.13380896,  0.80636418],
        [ 0.84339838, -0.89483332, -0.57876961],
        [-1.07174245,  0.6090676 ,  0.30689789],
        [-1.12745564, -0.95960827, -1.02682993],
        [ 2.00641118, -0.78972528, -0.55548682],
        [ 0.35242592, -0.10909891, -0.12006148],
        [-1.06129623,  2.73667723,  3.46206432],
        [ 0.22707124,  0.1587518 , -0.0329502 ],
        [-0.26041915, -0.361371  , -0.14301521],
        [-1.32593387,  1.85330294,  2.57358396],
        [ 0.51956548, -0.55601866, -0.46789452],
        [ 0.65536637, -0.87741078, -0.61781823],
        [-0.85933592,  2.7307565 ,  3.25895673],
        [-0.52157472, -0.66131907, -0.8483131 ],
        [-0.6190728 , -0.68491544, -0.73219838],
        [ 0.7598286 , -0.55961523, -0.49460145],
        [-0.06890507, -0.34851051, -0.15453244],
        [ 0.37331836,  0.45691547,  0.0663106 ],
        [-0.2673833 , -0.35386816, -0.12227823],
        [ 0.34197969, -0.25515253, -0.13061737],
        [-0.33702478,  0.48172376, -0.0869843 ],
        [-0.57380583, -0.55427402, -0.57627172],
        [-0.159439  ,  1.46069474,  0.01682902],
        [-0.5111285 , -0.67425852, -0.71989216],
        [-0.17684937,  0.98918436,  0.63805739],
        [-1.34334424,  1.13332265,  1.33626971],
        [-1.0787066 ,  0.13760978,  1.13928414],
        [-0.91156703,  0.79991814,  0.47965678],
        [ 2.45908083, -0.80450207, -0.55796991],
        [-1.04214482, -1.08215115, -0.8913853 ],
        [-0.58773413, -0.70165159, -0.73219838],
        [-0.65389354,  1.04974955,  1.12807915],
        [-0.97511489, -1.03394134, -1.08365921],
        [ 0.42554947, -0.6015766 , -0.33480128],
        [-1.14486601,  1.84696491,  2.05768266],
        [ 0.37331836, -0.4451596 , -0.18892649],
        [-1.42343195,  0.82598427,  0.93846717],
        [-1.01602926,  0.46793833,  0.28280209],
        [ 0.14698354, -0.24179477, -0.13947308],
        [-0.159439  , -0.35541496, -0.13127819],
        [ 0.12609109, -0.22413514, -0.13456171],
        [-0.91156703,  2.91042787,  3.21740456],
        [-0.77924821, -0.75862028, -0.68440704],
        [-1.15879431, -1.01305841, -1.03375715],
        [-0.36836345,  1.23236939,  0.87808582],
        [-0.99687785, -1.04742415, -1.04196106],
        [ 0.64840223, -0.30450203, -0.09539065],
        [-1.05085   ,  1.66373872,  1.81168908],
        [-1.0926349 , -0.93176383, -0.97836014],
        [ 0.44992399,  0.20008959, -0.01883962],
        [-0.87326422, -0.73206986, -0.711499  ],
        [ 2.10739133, -0.78731288, -0.60872384],
        [ 0.11216279,  1.57936879,  0.20762343],
        [ 1.71391694, -0.86407149, -0.59433613],
        [-0.49023605, -0.3905108 , -0.25461159],
        [-0.77576614,  0.45234931,  0.45973879],
        [-0.21515219,  1.33799728,  0.97947029],
        [-0.47282568,  0.49407065, -0.10749676],
        [-0.05497677, -0.31742492, -0.15079676],
        [-0.59818035, -0.69224792, -0.71989216],
        [-0.44148701, -0.69773107, -0.71681836]]),
 array([ 356.12923155,  495.15459443,  531.34918745, 1503.30453887,
         236.24540103, 2049.73095522,  804.83955054,  413.69890848,
         549.11012742,  520.95597207,  693.87214569, 2831.91327795,
         411.65606671,  699.08240924, 1527.16495771, 1772.45670873,
         370.33592298, 1994.66048009,  368.73333219,  280.61890112,
        2607.67101   , 1344.11172627,  420.51834094,  403.21911501,
         236.33615325, 1155.02833427,  741.13133503,  352.23302877,
         601.55124667,  664.00981004,  984.73163164,  230.36509257,
         468.91523067,  396.35617465,  579.23944444, 1919.70382594,
         543.66992293, 1678.17376131,  396.65677735,  225.48348857,
        1671.58702511,  292.47136256,  473.45855125,  376.95688775,
        1988.24849019, 1476.48459185, 2307.87743889, 1553.88149777,
        1068.56554679, 1714.24743761,  372.29190932, 2093.54197931,
        1379.81611483, 1010.60878813,  827.54366185,  254.21452472,
         412.83311987,  405.07872244,  366.65135788,  812.13257624,
         701.43668878, 1878.17986012,  716.29694683, 1132.70305504,
         472.29271216, 1597.72962177,  792.57716247, 1528.36240347,
        1607.37197626,  599.42736344, 1449.87247118,  449.34283769,
         462.9778131 ,  775.87995195,  700.39397318, 1648.21349589,
         374.76386993, 2212.69467778, 2871.07474273,  393.1807138 ,
         471.42215608,  197.03958729, 2014.61166217,  664.71944013,
         692.17837753,  657.14211911, 1850.61507526,  837.90716936,
         365.16752926,  404.21047056,  871.56469916,  800.23215088,
         431.18887878,  370.15236118,  674.8278768 , 2082.47565853,
        1784.02184338,  433.734496  ,  829.91853277, 2202.98566429,
         700.30586827,  354.20888767,  618.04660657,  376.389791  ,
         678.08791486, 1098.10983961,  558.16483166,  644.35546527,
         516.06921054, 1902.96087356,  416.5827464 , 2632.60958642,
         400.20800767, 1525.45544724, 1291.02769333,  754.93094741,
         733.93937642,  824.97908415, 2253.69922017, 1659.86385017,
        1311.02425943, 1682.01513072, 1483.27681152,  367.31464566,
         583.10748748, 1760.69052266, 2933.76282825, 2210.38981549,
         734.35926361,  695.57154841,  394.76792698,  989.14403412,
         408.04081236,  432.79509579,  380.52978408, 1640.98358014,
        2943.79967377, 1674.72932329,  205.9196225 ,  513.22612155,
        1563.36231507,  435.91406633, 1497.83984319,  347.54366667,
        1521.27763785,  534.74332348, 2159.36260451, 1981.1416827 ,
        1559.70688599,  514.79905625,  808.66669584, 2155.9055698 ,
         203.82581434, 1363.79190736,  234.29577301,  620.23790604,
         412.67568405, 2280.38343906,  724.45722066, 2798.87874242,
         843.28665645,  408.51946714,  380.62936341, 1668.25244927,
         502.09199094,  727.67912102,  221.45805736, 1642.58213546,
         833.0142566 , 2223.67080876,  305.88381483,  492.4222511 ,
        1295.62319317,  713.80122308,  393.79887448, 2961.86225073,
         762.25083302,  695.43655326,  202.807127  ,  477.42001085,
        1543.78960101, 2261.1524086 ,  444.80138925,  773.14899544,
         785.33292266,  256.54210132,  751.89105055,  497.30754934,
        2514.97781875,  849.03150206,  503.42216271, 1556.0151945 ,
         608.97031858, 1768.72803937,  730.25676011,  523.62063656,
         556.53304527,  621.23430417, 3146.54840026,  467.16477025,
         614.2999327 ,  443.40566517, 1037.2625308 ,  704.33492097,
         749.11095487, 2126.76603228, 1547.05808408,  244.84256067,
         720.64201471,  727.40027755,  235.38485029,  761.251426  ,
         416.32835069, 2817.0923303 ,  952.6741647 , 1626.14746919,
        2530.46532153, 1829.53840562,  319.43620996,  415.20445326,
         424.5468995 ,  642.87607148, 1534.10606037,  581.90996396,
         397.68925286, 1847.25208637,  726.47837419,  660.90846305,
         506.52384913,  368.63058577, 1845.83914348,  758.26037994,
        1396.27822444, 1823.60257365, 2338.15789393, 1406.81480797,
         669.10636269,  667.50746059,  582.14356199, 1614.80688216,
        2613.22209716,  480.14538518,  429.64924294, 1287.34256357,
        2296.15369124, 1397.23002902,  600.12102642, 1503.0615181 ,
         683.36296867,  921.87381943,  420.88285439, 2314.89467646,
         988.56613943,  597.21290368,  380.91050158,  663.47964581,
        2030.69587925,  423.02205429, 2849.10322956, 1489.93839359,
         732.00099497,  701.46629937,  379.84189435, 2231.10460268,
         390.79239419,  504.23185017,  721.72152087, 1434.79987397,
         629.93441916, 2024.69461736,  570.86201446, 1338.94976685,
         832.44653996,  599.64949948,  466.87724425,  379.45618834,
        1100.60487888, 2195.81316371,  625.66295526, 1660.4992794 ,
         773.96879941,  792.86326381,  685.48735093,  672.92463662,
        2219.08365685,  656.08209655, 1625.87393426,  471.88040948,
         379.33119715,  568.58143867,  743.04632394, 2070.7394168 ,
         382.27868235, 1285.12734595,  628.93987999,  485.19078498,
         378.34184462, 1730.62061056,  817.11485195,  759.04949781,
        1413.05696749,  751.46724834, 1329.5107776 ,  640.10428777,
        1401.90450191,  688.45726954,  725.07203973, 1835.73366925,
         620.03404639,  487.80236071,  700.48869818,  729.99302525,
         399.87845858,  594.47866245, 2329.55009608,  627.63642434,
         755.01146398,  449.16698952,  220.70364701,  461.88942341,
         381.8771327 , 3015.99935115,  752.26866311, 1198.04924475,
        1521.59123404,  257.46008987, 1814.87006082,  706.3035153 ,
        1818.93017581,  341.88727295, 1260.69043595,  771.97491309,
         619.54831144,  622.5189605 ,  187.97641888, 1298.17856288,
         619.99977406, 3043.83675162,  573.97186426,  220.70364701,
         441.27022826,  449.29672907,  240.59970009,  480.92963873,
        1502.70410902,  523.22333349,  394.14337976, 2349.50090041,
         612.28374491,  494.36735201,  325.23862537, 2995.96520991,
         432.12775494,  802.71095075,  305.61776402,  578.68853736,
         356.32988296,  392.31200339, 1834.92671987,  764.92393805,
        1356.34831323,  706.05489986, 2292.99695772, 2055.67211166,
        1556.47165467,  197.69227706, 2241.20158479,  430.22057699,
         716.98932341,  242.49956966,  465.5986947 ,  590.82423333,
        1595.25272401,  237.40203996,  398.47679023,  522.36512852,
         422.46325948,  565.21575263,  722.36195587,  659.41628039,
        1609.89882981, 3027.43846607, 2063.1637324 , 2263.65868775,
         649.0377975 ,  597.86656553,  640.21652291, 2840.75865258,
         591.92405506, 2702.07476091,  458.73963256,  675.08482014,
        3222.28857079, 1702.5984432 ,  598.10678734,  381.12145321,
        1486.5281851 , 2310.83060537, 1249.73150291,  435.56006924,
         618.03014027,  454.08830333,  429.40446502,  370.04160048,
         441.58489412,  557.84188207,  218.52818343,  397.00828223,
         297.76998727,  604.90339103,  806.85973511,  477.64202801,
         652.82534862,  766.4666983 ,  386.44936525, 2046.40396854,
         363.09877641, 1697.90288803,  446.80238348,  407.94299335,
         278.3902289 , 1630.43156786,  454.46161412, 1469.21718541,
        2240.72141965, 1571.37801883,  714.57239985,  234.39450701,
         796.81748797,  746.82838483, 1520.08542329, 1309.84905943,
         634.03236486, 1861.32839782, 1570.65312529,  776.17269725,
         623.83093561,  440.70873361,  234.49210613, 1630.30686461,
         325.88874974,  927.80184316,  554.75341338,  506.07704692,
        2074.20521819, 2129.38537506, 2021.94331362, 1578.87351264,
         242.13733092,  505.35686224, 1688.39399514, 1936.028766  ,
         719.48222532,  666.27900553, 2425.53398424,  669.07437652,
         679.89455016, 1761.02855894,  330.85635005,  670.8395517 ,
         426.90811592, 1543.17092787, 1684.46998669, 1515.39798533,
         482.44231998, 1559.70043079,  723.09624385,  246.70432398,
         692.12951489,  587.63366852,  635.03383211, 1431.5497857 ,
        2089.13579448, 1079.26984048,  561.01677108,  564.34543107,
         591.29159034,  561.2260473 , 1774.68220673,  413.27735672,
        2158.67285005,  706.62056453,  674.33593964, 2816.36501056,
        1348.59301055, 1892.59155209,  400.40492261, 2875.19027327,
        1611.18652924,  393.65382058,  469.09312848, 1614.67463664,
        2823.02806995,  804.55994532,  514.68708986, 1578.59111307,
        1894.3199896 , 2070.54727288, 1521.9027077 ,  584.3946755 ,
         366.34818057,  757.71645623, 1242.97300223, 1687.80459202,
         422.21029187,  655.11056848,  254.36261943, 1099.89974645,
         441.4523172 ,  418.47704762,  376.03981696,  294.7851049 ,
         241.91382191,  575.80871418,  795.55450584,  507.52643814,
         507.81235367, 1307.76089019,  513.61731775,  688.88119643,
         425.64719921, 1564.59886923,  630.32311328,  237.93626311,
         622.75135985,  388.35076011,  239.80513   ,  292.67303147,
         445.59156971,  617.58509567,  749.03298489,  316.70732881,
        2256.74680995, 1295.55745207,  235.97950675,  443.09410688,
         697.4899664 ,  663.95146005, 1807.01378121,  366.27441398,
         378.17809081,  231.40615806, 1579.18698409,  732.76352729,
        2740.6952109 , 1614.20797474,  414.38152362,  608.08595365,
         435.73417668,  232.93854897,  385.5909699 ,  409.05387699,
        1316.34327483, 2760.72747173,  340.70994288,  655.13249574,
         735.617207  ,  496.82416779,  441.07743817,  636.50366287,
         407.20037868,  724.91648089, 1515.14593614,  611.08000783,
         462.50041795,  423.97033081, 2201.36896814, 2093.35462329,
        1083.26146623,  723.15971149,  571.78074475,  743.26247106,
         750.53026967,  683.85754767, 1436.07090702, 2110.86612618,
         676.6265843 ,  568.12297681,  416.89378474,  724.74550681,
         577.60881239,  720.95941361, 1587.90566518, 2590.02003193,
         537.59262559,  334.33403051, 1863.43154681,  361.2016705 ,
        1736.60973752, 1119.1849315 ,  689.48179032, 2493.02799351,
         516.2446837 ,  487.91596458,  691.6576261 ,  544.35457322,
         710.2809163 ,  430.30250229,  669.51990648,  571.23889963,
         425.50059585,  426.37080721,  371.55455623,  707.58742983,
         583.92096872, 1262.20466394, 1611.9753724 ,  223.13114786,
         312.98382071, 2130.01128697, 2017.30786588, 2889.5499183 ,
         623.31956617, 2285.07149276,  897.07710925, 1463.52986301,
        1555.17172268,  726.93677929,  216.87932481,  363.01969942,
         587.1841251 ,  537.09215329,  599.91739357, 2149.6056218 ,
         713.42686068, 1524.62999412, 1221.52504847,  739.20278328,
        1680.84157669,  439.49248449, 1255.31854937,  407.25323647,
        2442.06103707, 1340.26623159,  481.61663873,  444.83949976,
         807.40723682, 1166.00512622,  579.96349375,  726.5930894 ,
         618.53150122, 1975.26284495,  587.34304263,  680.91564984,
        1754.26216139, 2213.21341782,  821.30211296, 1069.31106396,
         343.29180266,  367.36807342, 2551.21516699, 1534.20312803,
         490.0881854 , 1796.32644149,  724.2114926 ,  584.53223868,
         730.66091007,  711.15144976,  666.88569928,  464.04689945,
         719.66725255, 1611.27752444, 1593.95310491,  410.0682689 ,
         210.53941026, 1624.82415271,  739.01568785,  677.02620838,
         403.61364403,  589.75453235,  499.9235881 , 1607.61407068,
         494.54045221,  715.67381629,  530.24213527,  790.86815151,
         411.43601754,  224.2249054 ,  446.49929209, 1548.50371074,
         384.5901158 ,  315.48955999,  209.26490617,  602.65430277,
         366.20452702, 1600.56737401,  252.13065632, 1191.5803194 ,
         465.46026786,  469.93135573, 1093.01249151,  630.20870477,
         633.44580703,  377.59127509,  350.9092081 , 2221.92630642,
        1813.92899721,  739.43692732,  365.9939805 ,  491.72732297,
        1043.59891477,  641.66173777,  457.60454438,  205.24059811,
         390.85350051, 1209.06738299, 1528.93938493,  245.81880693,
        1219.42766157,  814.70376801, 1894.16805243,  230.26407274,
         244.35443755, 2132.03609683, 1730.48141142,  718.79753459,
         373.80860709,  720.58121848, 2287.21840231,  429.04643415,
         725.03103123,  324.23281098, 1495.62683473,  217.65948337,
         445.45571489,  384.82836572,  674.68315677, 1290.51652025,
        2262.06675622,  586.42096516, 2954.2920812 ,  459.53329974,
         675.36854374,  801.04705698,  475.66615674,  362.21721908,
         363.57199171,  608.69213447,  367.06859176,  677.33866627,
        1688.93535771, 1632.23724756,  597.96655021,  507.39602151,
         435.48462661,  268.73035942, 1083.54110656,  331.4536821 ,
         590.96952751,  581.6691401 ,  343.18874908,  410.33848826,
         553.3895039 ]),
 array([ 520.78081744,  640.44271534, 1993.77712188,  370.54140062,
         614.57681185, 1675.68930476,  493.9870231 , 1088.0701671 ,
        1692.84940111, 1613.60048196,  454.80283276,  390.42693044,
         725.86159663,  644.89595429, 1871.72493012,  614.22109116,
         412.33573595,  432.79022642,  428.16240246, 2905.60535082,
        1579.87558472,  392.53815923, 1303.92569563, 1833.93773832,
         336.84615207, 1518.11955747,  341.39331526,  440.36285921,
         953.14816614, 2941.11183721, 1111.99557036,  692.35203596,
        2327.7733222 ,  680.12838426,  417.44658941, 2700.05566192,
         533.27719127,  560.85150772,  563.65464451,  776.08267938,
        1424.9019323 ,  735.21047157,  802.02941576, 1228.71446708,
         586.4374851 , 1753.19964534,  482.65713775, 1645.44199565,
        1861.99410208, 1036.75140997, 1389.7617666 ,  380.75603072,
         232.4032458 ,  543.79504421, 1662.87421106,  254.68026024,
         634.39784718, 2312.27395408,  668.7435234 , 1620.19620739,
        1428.22525238,  817.48966856,  739.89674674,  808.79717081,
        2663.62001868,  438.58499674,  291.95605976, 1785.87216761,
         236.83734139,  770.0071113 , 2182.70245066,  359.1609971 ,
        1114.78265095,  438.28415855,  398.44482444, 2154.33707813,
         404.43219842,  737.26549668, 1351.580089  , 1920.80020372,
        1308.22011284,  781.97325   ,  469.97117139,  497.62734637])]

By completing this exercise, we have learned all the required steps for data preparation before performing a regression.